name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify Checked-out Code
        run: |
          git log -1
          ls -al

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-1

      - name: Debug AWS Identity
        run: |
          aws sts get-caller-identity
      
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 209479279888.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build --no-cache -t healthsync/sync-service .

      - name: Tag Docker image
        run: |
          docker tag healthsync/sync-service:latest 209479279888.dkr.ecr.ap-southeast-1.amazonaws.com/healthsync/sync-service:latest

      - name: Push Docker image to ECR
        run: |
          docker push 209479279888.dkr.ecr.ap-southeast-1.amazonaws.com/healthsync/sync-service:latest

      
